import { useRef } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

type Props = {
  inspection: any;
};

function InspectionReport({ inspection }: Props) {
  const reportRef = useRef<HTMLDivElement | null>(null);

  async function downloadPDF() {
    if (!reportRef.current) return;

    const canvas = await html2canvas(reportRef.current);
    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const imgHeight = (canvas.height * pageWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 0, 0, pageWidth, imgHeight);
    pdf.save(`${inspection?.inspection_no || "inspection-report"}.pdf`);
  }

  return (
    <div>
      <div ref={reportRef} style={report}>
        <h1>GTB1N Auto Detailing & Window Film</h1>
        <h2>Vehicle Inspection Report</h2>

        <hr />

        <p>Inspection No: {inspection?.inspection_no}</p>
        <p>Customer: {inspection?.customer_name}</p>
        <p>Phone: {inspection?.phone}</p>
        <p>Plate: {inspection?.plate_number}</p>
        <p>Vehicle: {inspection?.vehicle_model}</p>

        <hr />

        <h3>Damage Summary</h3>
        <p>{inspection?.damage_summary || "No damage recorded"}</p>

        <h3>Notes</h3>
        <p>{inspection?.condition_notes || "-"}</p>

        <hr />

        <p>Generated by GTB1N Auto Detailing & Window Film POS</p>
      </div>

      <button onClick={downloadPDF} style={btn}>
        下载 PDF 报告
      </button>
    </div>
  );
}

const report = {
  background: "#fff",
  color: "#111827",
  padding: 30,
  width: 800,
};

const btn = {
  marginTop: 16,
  padding: "14px 22px",
  border: "none",
  borderRadius: 12,
  background: "#111827",
  color: "#fff",
  cursor: "pointer",
};

export default InspectionReport;